### ISSUE TITLE
Location filter exclude ui-ux designer position in Prague

### ISSUE THREAD

**Issue by AlexSedymov** [sinnerschrader/sinnerschrader-career#275]
**Describe the bug**
Hello) 
(Prague) Location filter exclude _UI-UX designer position in Prague_ from results.

**To Reproduce**
1. Go to 'https://sinnerschrader.jobs/en/'
2. Click on 'Prague' location filter
3. UX/UI Designer position in Prague not listed

**Solution**
Change location short key from Prague to Pra:
https://github.com/sinnerschrader/sinnerschrader-career/blob/main/data/jobs/en/ux-ui-designer-prg.md

Thank you )

**Comment by chaosmonster** [comment]
Thank you - will fix that
